export const FETCH_USUARIO_REQUEST = 'FETCH_USUARIO_REQUEST'
export const FETCH_USUARIO_SUCCESS = 'FETCH_USUARIO_SUCCESS'
export const FETCH_USUARIO_ERROR = 'FETCH_USUARIO_ERROR'
export const FETCH_CLEAR_STATE = 'FETCH_CLEAR_STATE'
export const CLEAR_STATE = 'CLEAR_STATE'

export const FETCH_REGISTRO_SUCCESS = 'FETCH_REGISTRO_SUCCESS'
export const FETCH_REGISTRO_ERROR = 'FETCH_REGISTRO_ERROR'
